version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
    # Something about the newly-released version 4 of the R image breaks
    # deployment to Google Cloud Run (it can't find executables
    # for CMD/ENTRYPOINT).
    # Hoping they fix it by the time they get to 4.1,
    # because I couldn't figure it out
    - dependency-name: rocker/tidyverse
      versions: [4.0.x]
