sudo: required
services:
  - docker
env:
  global:
    GOOGLE_APPLICATION_CREDENTIALS: .gcloud/keyfile.json
before_script:
  - docker pull cfranklin11/tipresias_afl_data:latest
  # R packages take forever to install, so we give it 30 minutes before timing out
  - travis_wait 30 docker build --cache-from cfranklin11/tipresias_afl_data:latest -t cfranklin11/tipresias_afl_data:latest -f ./ci.Dockerfile .
script:
  - docker-compose -f docker-compose.ci.yml up -d
  - ./scripts/wait-for-it.sh localhost:8050 -- echo "Splash ready"
  - docker-compose -f docker-compose.ci.yml run app Rscript -e "devtools::check(check_dir = '.')"
before_deploy:
  # Set up authentication
  - openssl aes-256-cbc -K $encrypted_241002f0ef4b_key -iv $encrypted_241002f0ef4b_iv -in keyfile.json.enc -out keyfile.json -d
  - mkdir ${PWD}/.gcloud && mv keyfile.json ${GOOGLE_APPLICATION_CREDENTIALS}
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  # Push image
  - docker push cfranklin11/tipresias_afl_data:latest
  # Prepare gcloud tool for deployment
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components install beta
  - gcloud --quiet components update
  - gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
  - gcloud --quiet config set project $PROJECT_ID
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: main
