sudo: required
services:
  - docker
env:
  IP_ADDRESS: 167.71.212.75
before_script:
  - docker pull cfranklin11/tipresias_afl_data:latest
  # R packages take forever to install, so we give it 30 minutes before timing out
  - travis_wait 30 docker build --cache-from cfranklin11/tipresias_afl_data:latest -t cfranklin11/tipresias_afl_data:latest -f ./afl_data/ci.Dockerfile ./afl_data
script:
  - docker-compose -f docker-compose.ci.yml up -d
  - ./scripts/wait-for-it.sh localhost:4444 -- docker-compose -f docker-compose.ci.yml run app Rscript -e "devtools::test()"
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_afl_data:latest
  - openssl aes-256-cbc -K $encrypted_b3ce34c885bd_key -iv $encrypted_b3ce34c885bd_iv -in deploy_rsa.enc -out ${HOME}/.ssh/deploy_rsa -d
  - ssh-keyscan -H ${IP_ADDRESS} >> ${HOME}/.ssh/known_hosts
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
