sudo: required
services:
  - docker
before_install:
  - mkdir .gcloud
  - openssl aes-256-cbc -K $encrypted_b3ce34c885bd_key -iv $encrypted_b3ce34c885bd_iv -in keyfile.json.enc -out .gcloud/keyfile.json -d
before_script:
  - docker pull cfranklin11/tipresias_afl_data:latest
  - docker build --cache-from cfranklin11/tipresias_afl_data:latest -t cfranklin11/tipresias_afl_data:latest -f ./afl_data/ci.Dockerfile ./afl_data
script:
  - docker run cfranklin11/tipresias_afl_data:latest Rscript -e "devtools::test()"
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u cfranklin11 --password-stdin
  - docker push cfranklin11/tipresias_afl_data:latest
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components install beta
  - gcloud --quiet components update
deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master
