version: "3.2"
services:
  app:
    image: cfranklin11/tipresias_afl_data:latest
    environment:
      - R_ENV=development
      - CI=true
    ports:
      - "8080:8080"
    command: Rscript app.R
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    # String matching functions aren't available in sandbox mode for some reason
    command: --disable-lua-sandbox
