version: "3.2"
services:
  app:
    build: .
    volumes:
      - ./afl_data:/app
    env_file: .env
    environment:
      - R_ENV=production
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    # String matching functions aren't available in sandbox mode for some reason
    command: --disable-lua-sandbox
