version: "3.2"
services:
  app:
    image: cfranklin11/tipresias_afl_data:latest
    environment:
      - R_ENV=production
    env_file: .env
    ports:
      - "8080:8080"
    command: Rscript app.R
