version: "3.2"
services:
  app:
    build: ./afl_data
    volumes:
      - ./afl_data:/app/afl_data
    depends_on:
      - browser
    env_file: .env
    environment:
      - R_ENV=development
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
  browser:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - "4444:4444"
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    # String matching functions aren't available in sandbox mode for some reason
    command: --disable-lua-sandbox
