version: "3.2"
services:
  app:
    build: .
    volumes:
      - ./afl_data:/app
    env_file: .env
    environment:
      - R_ENV=development
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
