version: "3.2"
services:
  app:
    build: ./afl_data
    volumes:
      - ./afl_data:/app/afl_data
    env_file:
      .env
    environment:
      - R_ENV=development
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
